modLoader="javafml"
loaderVersion="${loader_version_range}"

license="${mod_license}"
issueTrackerURL="https://github.com/pixelgamewizard/pgwbandedtorches/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/pixelgamewizards-banded-torches"
logoFile="pgwbandedtorches_logo.png"
authors="${mod_authors}"

description="${mod_description}"

[[dependencies.${mod_id}]]
  modId="neoforge"
  mandatory=true
  versionRange="${neo_version_range}"
  ordering="NONE"
  side="BOTH"

[[dependencies.${mod_id}]]
  modId="minecraft"
  mandatory=true
  versionRange="${minecraft_version_range}"
  ordering="NONE"
  side="BOTH"

