modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/pixelgamewizard/pgwbandedtorches/issues"

[[mods]]
modId="pgwbandedtorches"
version="${file.jarVersion}"
displayName="PixelGameWizard's Banded Torches"
displayURL="https://www.curseforge.com/minecraft/mc-mods/pixelgamewizards-banded-torches"
logoFile="pgwbandedtorches_logo.png"
# credits="Thanks for this mod goes to ..."
authors="PixelGameWizard" #optional
description='''
This is a simple mod to add varied torches. The torches appear similar to those of regular Minecraft, except there is a colourful band.

What that band means is up to you - maybe it was left by specific player, or maybe it has some other meaning!
'''

